apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gin-vue-2022-06-01t21-13-45
spec:
  encryptedData:
    .dockerconfigjson: AgBV7dnCvd3NXlnsM75k7fVrfLOYjAupv9mk6lYbOpb9a72L8fna+XQEHZa7sgjn93Frwm7SXh6K8QNytwNITu0uGjcEPfqdgUM2pV8/rOHPSqVoS4EIK+g9qD4K/GO+x0SvEVU1Osx6xE0QGqA588UPZFXYZ9VbsXN1yP3VhA7/BSpHIkNeQ4PKdKrZq6NZm08PxD9y0acsolzpYQDy51KnU1aBNyWA9Qqo3KYXw81GET9stMJqvCO7rjwq+DjO3dqfL60gXh8h85Ue8+2ChsWZmPUz3iRRBzdf+JTUDctVTdjiMbt1gQa6HXtYO6QDSKU++baX5J4vntrbkMJzBdA4KHua5dCFBHKGe5MsM2UAtATWU/VcOGAWNxYUOT9ePB7i/UX20Sb82Xl8UsnAqaDlIUKDEU+QD93hvQKNpeHqiQPvRFjcIPdFkCH2X7rmCZdrkvCRbLbT2lJydKRvWxo9vfudFJKNn/hJJkPhfyYXt7RP0FWttqkZ+1vyJNKgfAJ15tkL0OkjmETJft7yTC1MBHIj97kYI8RI8ntLySdHjj2uwtyOvPAF7bmIK1lcsxWAol8k9xip3mEfu78yHRsANJIKHhUFIiyc3prySD+fIzLOsYg17HjWgtcsGNAdy1toUdAUDqbAOFrDNxzLCGAAz23U9z0imY5rxstqWZmoz84Yz+haoNfpUFmlrlgubsiB2bL6x/Bg6CJdngUESri2An9nz0yfYn96wgSP6t3q6pWc/p39PHsLSD3VdqHfzSNc+U7Me0dHx2yBS2daJg40puuYKDgcW5keBtZjDDLU1LreJ50P7XdNH+zHdusxIKT3W83m5/X0eTYiK2oXKoVgJYw1e2qWvFDAIPml9o65AQc8HBpz7Q+6Es/+cJxg1YI537+Yil/KMRfji5lSqLsAGwbJtujWKsPlkiJTXxznQQUZFKncgroJxrzCrCk/r+o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gin-vue-2022-06-01t21-13-45
    type: kubernetes.io/dockerconfigjson

